glacials/whatsinstandard

README.md, api/1/sets.json, api/2/sets.json, api/3/sets.json
Looks like when the logos were converted from JPG to SVG, the API JSONs weren't updated, so this takes care of that.
=> Correct JPG -> SVG links in API

README.md
http://www.wizards.com/magic/magazine/article.aspx?x=judge/resources/sfrstandard redirects to an archived page. I have updated the link to a current page regarding the Standard format.
=> Updated README to show non-archived webpage

README.md, img/bng.svg, img/ths.svg, index.html
I thought it might be nice to have the latest sets that were rotated out of Standard listed on the page. The image below is a quick screen cap of what was added in the merge.
=> Rotated out list

css/style.css, index.html
- fixes issue with moving github logo
- moved logo to bottom of right column
- removed footer
fixes: https://github.com/glacials/whatsinstandard/issues/21
* checked on mobile chrome as well
=> fixes issue with bouncing github logo

index.html
This is targeted to fix issue #31.
Some things I have questions about:
- I don't know of any high quality SVG set symbols for *Kaladesh* or *Aether Revolt* yet, so their icons have been omitted.
- Both sets have had their release dates announced, so I attached two `.label-default` elements to the appropriate `.list-group`. It looks okay to me, but it might not be the best solution for the annotation.
Thanks!
=> Add Kaladesh and Aether Revolt sets. Addresses #31

index.html
Includes an additional sentence clarifying that non-standard
sets are not in Standard, a tooltip with a specific example
pointing to masters sets, and a link to the official wizards
standard list.
Attempts to fix #28 
From #40
=> feat(is-standard): include clarification of what is standard

index.html, js/app.js
Hey. I really like this site, but the lack of set icons was bothering me. I looked into it a bit and saw that they were there already, but weren't being displayed for some reason. It appears that the issue was somewhere in the bootstrap tooltip components you were using. 
To fix it, I tried to match the style used for the ban list icons. It appears the intent of the tooltip was to provide the set abbreviation on hover, so I left it as that.
This is my first time with both Vue and creating a PR across forks, so let me know what else I can do to make this mergeable.
Again -- Thanks for making this site! It has helped me on a few occasions.
=> fix set icons

api/v5/sets.json
Added exit_date to Kaladesh, Aether Revolt, Amonketh, Welcome Deck 2017 and Hour of Devistation since they will rotate when Guilds of Ravnica is added.
=> Add exit_dates

index.html
I feel like the term `recently` suggests/implies a short(er) time frame, while `last` is more general and accurate.
It's weird to drop down that list and read *10 month ago...*
<br>
(No native speaker here. So I might be wrong about the exact meaning, but it shows the confusion at least)
=> rename 'recently' to 'last'

api/internal.json
It's called `Core Set 2019` officially:
https://magic.wizards.com/en/products/core-2019
Realized that it's displayed wrongly on the webpage.
=> correct m19 set name

index.html
fixing https://github.com/glacials/whatsinstandard/issues/96
In the list of all standard sets hovering the set icon will show it's code.
In the list of banned cards it'll show the full name instead. While that makes sense in a way, it still misses that information.
Sometimes you need to know the code over, or in addition to, the full name.
People always confused `IXL` and `XLN` for Ixalan for example.
=> bans: add set codes to tip box

index.html
I added `target="_blank"` to all links introduced in https://github.com/glacials/whatsinstandard/pull/109.
Just like the linking of banned cards, it opens scryfall for set overviews in a new page now too.
Please check if I missed something.
=> make scryfall consistently open in new page

api/internal.json
- Right now the site shows XLN, RIX, DOM and M19 as leaving in 4 months, while it says that Throne of Eldraine releases in 2 months. 
Now that we know the expected release date for Throne of Eldraine, is there a reason why these 2 dates shouldn't match?
I updated their exit dates so that this is kept consistent.
- I also added Throne of Eldraine's [confirmed](https://markrosewater.tumblr.com/post/186410356343/whats-the-three-letter-abbreviation-for-thrones) three letter code
=> Update XLN, RIX, DOM and M19 exit date to match ELD enter date

css/style.css, index.html, js/app.js
This fixes  [issue #156](https://github.com/glacials/whatsinstandard/issues/156) by giving all sets the faded-out border that sets currently in Standard have, and giving a thicker and darker border on-hover for every set to keep that sensation of "about to click a button."
=> Fix Border on-hover issue for sets not yet in Standard

api/internal.json
Hello :)
This PR contains an update following the [1st June announcement](https://magic.wizards.com/en/articles/archive/news/june-1-2020-banned-and-restricted-announcement). It includes Agent of Treachery and Fires of Invention.
Both reasons are homemade based on the announcement. Feel free to comment any improvement.
cheers
=> Add Angent of Treachery and Fires of Invention to the banned list

api/internal.json
https://wpn.wizards.com/en/article/store-play-suspension-temporarily-reinstated-us-latam gave us prerelease dates, and release is the following week
=> Zendikar Rising release date

index.html
Currently the button implies that the hidden sets just left shortly. But reality is that those sets left a year ago already...
=> Clarify wording on left sets button

index.html, js/app.js
Fixes: #165 
The `.set-border` class that is being used for the sets that are in Standard, or about to be, was applied to sets that have left. This added the border, and also applied a "jumping" effect. Just removing that selector got rid of the borders and the jumping for me, locally. 
Let me know if this looks okay for you, or if there is anything else I should do.
=> Hide left sets layout problem

api/internal.json, api/v5/generate.js, test/api.js
I added Names and rough dates for the two sets following Kaldheim.
I also had to fix the v5 generator, because it was failing tests.
Didn't add the Q4 set(s), because I don't know how we want to represent them yet. I think we just wait for WotC to give us more details.
=> Add known data about Strixhaven and Adventures in the Forgotten Realms.

index.html
<kbd>Hide</kbd> → <kbd>Hide left sets</kbd>
Buttons should also be of ~similar size now as a side effect.
=> Hide button: Explain what is hidden

api/internal.json
Source: https://magic.wizards.com/en/articles/archive/feature/what-happened-magic-showcase-2021-08-24
=> Add initial data for 2022 Standard sets

web/api/internal.json
This commit updates the banlist for standard, removing what rotated out
already, and adding the cards announced on 2022-01-25.
Cards added:
- Divide by Zero
- Faceless Haven
- Alrund's Epiphany
Cards removed:
- Cauldron Familiar
- Escape to the Wilds
- Fires of Invention
- Lucky Clover
- Oko, Thief of Crowns
- Once Upon a Time
- Uro, Titan of Nature's Wrath
=> Update standard banned list for January 25th annoucement

web/api/internal.json
Source: https://magic.wizards.com/en/articles/archive/news/your-sneak-peek-double-masters-2022-dominaria-united-and-beyond-2022-05-12 (Literally the same article as #231)
=> Add Brothers War release date

web/api/internal.json
Closes #238
Source: https://magic.wizards.com/en/articles/archive/news/october-10-2022-banned-and-restricted-announcement
=> Add The Meathook Massacre to banned cards

web/api/internal.json
WotC pushed it back one week (announced in the Dec 6 twitch stream)
=> Update Phyrexia: All Will Be One release date to new date

web/api/internal.json
The enter date is back to 2023-02-03, as WotC changed Standard format legality shifts.
Source: https://magic.wizards.com/en/news/announcements/format-legality-shifts-to-prerelease-with-phyrexia-all-will-be-one
=> Update Phyrexia: All Will Be One enter date

web/api/internal.json
Source: https://magic.wizards.com/en/news/announcements/march-of-the-machine-arrives-in-2023
=> Add March of the Machine: The Aftermath set code and enter date

web/api/internal.json
It belongs to the same Standard rotation as March of the Machine.
> MOM: Aftermath is a new thing and not a normal expansion.
Source: https://markrosewater.tumblr.com/post/700372166964822016/what-are-you-counting-exactly-sorry-i-didnt
=> Fix March of the Machine: The Aftermath rough exit date

web/api/internal.json
https://magic.wizards.com/en/news/announcements/on-september-8-be-ready-for-wilds-of-eldraine
=> Wilds of Eldraine info

web/api/internal.json
See [Revitalizing Standard](https://magic.wizards.com/en/news/announcements/revitalizing-standard) and [Updates to Standard and Alchemy on MTG Arena](https://magic.wizards.com/en/news/mtg-arena/updates-to-standard-and-alchemy-on-mtg-arena).
Part of #259
=> Standard rotation is every 3 years from now on

web/api/internal.json
Fable of the Mirror-Breaker, Invoke Despair, and Reckoner Bankbuster are now banned.
Source: https://magic.wizards.com/en/news/announcements/may-29-2023-banned-and-restricted-announcement
=> Add bans from 2023-05-29: Fable, Invoke Despair, and Bankbuster

web/api/internal.json
https://magic.wizards.com/en/news/announcements/the-lost-caverns-of-ixalan-arrives-november-17-2023
=> Lost Caverns of Ixalan code and release date

web/api/internal.json
Source: https://wpn.wizards.com/en/news/magic-at-gencon-celebrating-30-years-and-casting-foresee-on-years-ahead
=> Add future codenames

web/api/internal.json, web/package-lock.json, web/package.json, web/src/types/card/Round.js
- Modified the timeline based on the new rotation rules
https://magic.wizards.com/en/news/announcements/aligning-the-universes-making-all-our-sets-legal-in-all-our-formats
- Update keyrune version
- Show one more rotation round (temporary I think)
PS: Maybe the rotation date can be clearer now, such as when the first set of 2027 releases?
=> Change to the new Rotation 2027

web/api/internal.json
Per issue #300, this pull request is to add the bonus sheet set [_The Big Score_](https://mtg.fandom.com/wiki/Outlaws_of_Thunder_Junction/The_Big_Score) (BIG) from [_Outlaws of Thunder Junction_](https://mtg.fandom.com/wiki/Outlaws_of_Thunder_Junction) (OTJ).
The BIG bonus sheet contains 30 Standard legal cards (all mythic rare). Due to the way the set came about, _Outlaws of Thunder Junction_ has another, non-Standard legal bonus sheet - [_Breaking News_](https://mtg.fandom.com/wiki/Outlaws_of_Thunder_Junction/Breaking_News) - and having the two be lumped under OTJ in the whatsinstandard listmay cause confusion for players unaware of the difference.
=> Add The Big Score (BIG) to set list

web/api/internal.json
Partially revert https://github.com/glacials/whatsinstandard/commit/03f0ac4b0df588987b1a13a00d5354ad316fac65
As per chapter 6.3:
https://media.wizards.com/ContentResources/WPN/MTG_MTR_2025_Apr%2021_EN.pdf
> The following card sets are permitted in Standard tournaments
> [...]
> - Edge of Eternities (effective July 25, 2025)
=> fix: 2025 exit date

mobile/lib/widgets/blocks.dart, mobile/lib/widgets/navigation_container.dart, web/src/components/SetListItem.vue, web/src/types/card/CardSet.js, web/src/types/card/Round.js
As the release date and enter date are not the same anymore since sets enter Standard on their prerelease date since last year use the word *enter* instead of *release* for sets that haven't entered Standard yet.
Rename the method used to determine if a set has entered accordingly.
See also #270.
=> fix: language for enter date

web/api/internal.json
As per chapter 6.3 of
https://media.wizards.com/ContentResources/WPN/MTG_MTR_2025_Apr%2021_EN.pdf:
> The following card sets are permitted in Standard tournaments
> [...]
> - Edge of Eternities (effective July 25, 2025)
=> fix: EOE enter date

web/api/internal.json
Enter dates since MOM are equivalent to the prerelease date and not the release date.
Sources:
- https://magic.wizards.com/en/news/announcements/format-legality-shifts-to-prerelease-with-phyrexia-all-will-be-one
- https://magic.wizards.com/en/news/announcements/march-of-the-machine-arrives-in-2023
- https://wpn.wizards.com/en/event/prerelease-march-of-the-machine
- https://wpn.wizards.com/en/event/prerelease-the-lost-caverns-of-ixalan
- https://magic.wizards.com/en/news/announcements/on-september-8-be-ready-for-wilds-of-eldraine
- https://wpn.wizards.com/en/event/prerelease-wilds-of-eldraine
- https://wpn.wizards.com/en/event/prerelease-murders-at-karlov-manor
- https://wpn.wizards.com/en/event/prerelease-outlaws-of-thunder-junction
- …
=> fix: enter dates since MOM are equivalent to the prerelease date

web/api/internal.json
Added _Through the Omenpaths_ (OM1) as a top level set.
This set is the Universes Within equivalent of Marvel's Spider-Man for _Magic Online_ (MTGO) and _Magic: The Gathering Arena_ (MTGA).
=> Update internal.json - Added OM1

web/api/internal.json
- add unknown Universes Beyond Set after Lorwyn Eclipsed
- more precise rough enter date for Secrets of Strixhaven
- add Marvel Super Heroes
- add The Hobbit
- add Reality Fracture
- Star Trek
source: https://magic.wizards.com/en/news/announcements/everything-announced-for-magic-the-gathering-in-2026
=> add more 2026 sets and update information
