index.html
=> Add Magic Origins name and release date

index.html
=> Add Oath of the Gatewatch

index.html
=> Add Shadows over Innistrad with release date

index.html
=> Add Eldritch Moon

css/style.css, index.html
Uses same formatting/style as bdzs/whatsinstandard#1.
Closes glacials/whatsinstandard#23
=> Add crosslink to Hearthstone What's in Standard

bower.json, css/style.css, index.html
Hey @glacials,
Not sure what you think about this but I threw this together in a few and thought I would just submit a PR so you'd have a better idea.
1. Converted all your set icons to the Keyrune icon font. More here: http://andrewgioia.github.io/Keyrune/
2. Deleted all your SVG set icons. Less file requests on load.
3. Moved your dropped sets toggle JS after the tipsy call to reduce JS file request.  If you get more javascript I would probably put it in a standalone JS file.
Regards,
Reece
=> icon fonts and miscellaneous stuff

index.html
Standard bans announced Jan 9, 2017
Effective Jan 11, 2017 MTGO; Jan 20, 2017 paper
=> Added Jan 2017 B&R updates

index.html
=> feat(banlist): add felidar guardian

index.html
Adds tooltips with the set codes to the icons
Fixes #38 
From #40
=> feat(icons): Add Set code to icons in list

api/4/sets.json
Address #50 
Just fix the exit dates for the sets.
=> Update exit date for bfz and ogw

index.html
http://magic.wizards.com/en/articles/archive/feature/june-13-2017-banned-and-restricted-announcement-2017-06-13
=> Aetherworks Marvel Ban

index.html
http://magic.wizards.com/en/articles/archive/making-magic/metamorphosis-2-0-2017-06-12
Wanted to help provide an update with the new metamorphosis 2.0.
=> Updated with Metamorphosis 2.0

index.html
https://magic.wizards.com/en/articles/archive/news/january-15-2018-banned-and-restricted-announcement-2018-01-15
=> Update with January 2018 B&R announcement

api/v5/sets.json
The date is not final since we don't know the exact release date yet. But it will be released sometime in January.
=> Add Ravnica Allegiance

index.html
=> Change URLs of format descriptions

index.html
=> Give additional examples of sets that don't enter Standard

css/style.css, index.html
Also links "All Sets in Standard" to a Scryfall search for "format:standard".
Fixes #108.
=> Link sets to Scryfall set pages

package-lock.json, package.json
=> Add RNA icon

api/internal.json
=> Add War of the Spark

package-lock.json, package.json
Updated version of keyrune to include M20 icon
=> Add M20 icon

api/internal.json
=> The name of the fall set (Archery) is now known.

api/internal.json
Adds new bans based on the August 3rd, 2020 updates: https://magic.wizards.com/en/articles/archive/news/august-8-2020-banned-and-restricted-announcement
=> Update banlist based on August 3, 2020 updates

index.html
Fixes #154.
I did some text rephrasing which removes the repetitive term ~10 times.
Please double check and make further suggestions on wording!
=> Remove the quantity of "Standard"

api/internal.json
Source: https://wpn.wizards.com/en/event/prerelease-kaldheim
=> Add exact release date for Strixhaven

api/internal.json
Sources:
- https://magic.wizards.com/en/articles/archive/news/strixhaven-school-mages-previews-and-more-2021-magic-release-dates-2021-03-18
- https://mtg.fandom.com/wiki/Innistrad:_Midnight_Hunt
- https://mtg.fandom.com/wiki/Innistrad:_Crimson_Vow
=> Update sets with new information

api/internal.json
Source: https://magic.wizards.com/en/mtgo/premier-play-2021
=> Add setcode for Forgotten Realms

api/internal.json
Source: https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets#Expansion_sets
=> Add code name Zebra for Adventures in the Forgotten Realms

api/internal.json
Source: https://wpn.wizards.com/en/article/mark-your-calendars-important-dates-kamigawa-neon-dynasty
=> Add exact enter data for Kamigawa: Neon Dynasty

api/internal.json
Source: https://magic.wizards.com/en/articles/archive/making-magic/vow-part-1-2021-11-01
=> Add codename Hockey for Kamigawa: Neon Dynasty

api/internal.json
https://twitter.com/wizards_magic/status/1463197702284402688
=> Kamigawa: Neon Dynasty is NEO

web/api/internal.json
=> More details for Streets of New Capenna

web/api/internal.json
Source: https://magic.wizards.com/en/articles/archive/making-magic/vow-part-2-2021-11-08
=> Add code name "Ice Skating" to Streets of New Capenna

web/api/internal.json
Source: https://magic.wizards.com/en/articles/archive/news/your-sneak-peek-double-masters-2022-dominaria-united-and-beyond-2022-05-12
=> Add Dominaria United set code and enter date

web/api/internal.json
Sources: 
- https://magic.wizards.com/en/articles/archive/magic-digital/mtg-arena-renewal-rotation
- https://magic.wizards.com/en/articles/archive/news/your-sneak-peek-double-masters-2022-dominaria-united-and-beyond-2022-05-12
=> Add exit date for ZNR, KHM, STX and AFR

web/api/internal.json
- Phyrexia: All Will Be One
- March of the Machine
- March of the Machine: The Aftermath
- Wilds of Eldraine
- The Lost Caverns of Ixalan
Source: https://www.youtube.com/watch?v=e5nuFEeGNsA&t=2214s
=> Add new standard sets from Q1 2023 until Q1 2024

web/api/internal.json
source: https://www.amazon.com/dp/B0B841ZL68/ref=cm_sw_r_apa_i_4XMQ90V6N93RPD2106PX_0
=> Brother's War setcode

web/api/internal.json
Source: https://magic.wizards.com/en/news/feature/phyrexia-all-will-be-one-is-coming
=> Add Phyrexia: All Will Be One release date

web/api/internal.json
Fix typo in Phyrexia: All Will Be One release date introduced in #237.
=> Fix typo in Phyrexia: All Will Be One release date

web/api/internal.json
https://wpn.wizards.com/en/products/march-of-the-machine
I also filled out a bunch of missing codenames while I was in there.
=> MOM code and release date

web/api/internal.json
https://magic.wizards.com/en/news/announcements/murders-at-karlov-manor-arrives-february-9-2024
=> Release date for Murders at Karlov Mansion

web/src/types/BiDate.ts
=> Calculate the date for "Q1 2024", "Q2 2024", etc. correctly

web/api/internal.json
Source: https://magic.wizards.com/en/news/announcements/a-first-look-at-bloomburrow
=> Add Bloomburrow release date and set code

web/api/internal.json
Source: https://magic.wizards.com/en/news/announcements/first-look-at-duskmourn-house-of-horror
=> Update Duskmourn: House of Horror information

web/api/internal.json
Sources:
- name: https://x.com/wizards_magic/status/1849911605750006231
- set code: https://x.com/wizards_magic/status/1849911211380596779
=> Aetherdrift: add name and set code

web/api/internal.json
Add names, set codes and enter dates.
Sources:
- https://x.com/wizards_magic/status/1849916158805409867
- https://x.com/wizards_magic/status/1849911211380596779
=> Add information about Tarkir: Dragonstorm and Edge of Eternities

web/src/components/SetListItem.vue
=> Update MTG Wiki URL
